# conda env create --file environment.yml

name: computervision_cnn
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pathlib
  - pip
  - plotly
  - pyprojroot
  - python=3.9
  - scipy
  - seaborn
  - scikit-learn
  - pip:
    - albumentations==1.2.0
    - opencv-python-headless==4.7.0.72
    - pyhere